### ISSUE TITLE
Add More Docs

### ISSUE THREAD

**Issue by alanJames00** [alanJames00/LinkZip#1]
Most of the endpoints that are newly added  are not documented. Needs more concise documentation. One can obtain information by referring to the code and inline comments in /api/routes.js file. Thanks

**Comment by cyberdad68** [comment]
i would like to work on this issue,Could you assign me this.

**Comment by alanJames00** [comment]
@cyberdad68 sure man. Let me know if you need any help.
Don't forget to star the repo and follow me.
