### ISSUE TITLE
need help on how to use this thing.

### ISSUE THREAD

**Issue by AaravMehta59** [alanJames00/LinkZip#11]
I had a question, how do you use the shorter URL format, 
like https://example.com/shorten?url=https://example.com/
is that supported, if not, then how to use the API?

**Comment by alanJames00** [comment]
@AaravMehta59 Can you make it more clear ? Are you trying to create a url or fetching a url that's already shortened ?
If you can't find the answer in readme just put a comment on this issue. Happy to help!

**Comment by alanJames00** [comment]
@AaravMehta59 If you don't have any questions, this issue may be closed.

**Comment by alanJames00** [comment]
Since there are now follow-up questions, this issue is closed.

**Comment by AaravMehta59** [comment]
> @AaravMehta59 Are you trying to create a url or fetching a url that's already shortened ? 

I am trying to create a URL. Sorry for late response

**Comment by AaravMehta59** [comment]
Exactly, I need to know that, Can we access the API using URL Queries (/shorted?url=url). If no, then how to access the API in order to create a link.

**Comment by alanJames00** [comment]
Step 1: Create a short url by making a POST request to  https://lz.linkzip.co/shorten with  json body 
```json
{
  "url": "https://example.com",
  "shorturl": "exmpl89"
}
```
Step 2:  Access the shortened url by going to: https://lz.linkzip.co/exmpl89

Hope that's useful.
